apiVersion: v1
kind: Service
metadata:
  name: iam-service
  annotations:
    prometheus.io/port: "http"
    prometheus.io/scrape: "true"
  labels:
    app: iam-service
spec:
  selector:
    app: iam-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
