apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
- name: gcp-sa-key
  options:
    disableNameSuffixHash: true
  files: 
  - secret-key.json

resources:
- external-secret.yaml