version: '3.8'

services:
  iam-service:
    build: ./iam-service
    ports:
      - "3001:3001"
    env_file:
      - ./iam-service/.env.example
    depends_on:
      - mongo
    networks:
      - microservices-net

  api-service:
    build: ./api-service
    ports:
      - "8000:8000"
    env_file:
      - ./api-service/.env.example
    depends_on:
      - iam-service
      - image-service
      - mongo
    networks:
      - microservices-net

  image-service:
    build: ./image-service
    ports:
      - "3002:3002"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp/keys/gcs-sa-key.json
      - GCS_BUCKET_NAME=tha-assets-store
    volumes:
      - ../thm-assess-sa.json:/etc/gcp/keys/gcs-sa-key.json
    networks:
      - microservices-net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
