apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: image-service
        image: europe-west1-docker.pkg.dev/thmanyah-assessment/thm-assessment/assessment-image-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcp/keys/gcs-sa-key.json
        - name: GCS_BUCKET_NAME
          value: tha-assets-store
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: gcs-sa-key
          mountPath: /etc/gcp/keys
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: gcs-sa-key
        secret:
          secretName: cluster-secret-store
          items:
          - key: GCS_SA_KEY_JSON
            path: gcs-sa-key.json
