apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-service
resources:
- deployment.yaml
- service.yaml
- poddisruptionbudget.yaml
- horizontalpodautoscaler.yaml
- networkpolicy.yaml
- namespace.yaml
components:
- ../_Components/SharedSecrets
